export default {
  SET_TOKEN: "SET_TOKEN",
  SET_QUERY: "SET_QUERY",
  SET_SERVER_INIT_RESPONSE: "SET_SERVER_INIT_RESPONSE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_PAGE_ITEMS: "SET_PAGE_ITEMS",
};
