export default mapping = {
  SET_CURRENT_PATH: "SET_CURRENT_PATH",
  SET_TOKEN: "SET_TOKEN",
  SET_PAGE_ITEMS: "SET_PAGE_ITEMS",
  SET_TOTAL_PAGE: "SET_TOTAL_PAGE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_KEYWORD: "SET_KEYWORD",
  VIEW_IMAGE_MODEL: "VIEW_IMAGE_MODEL",
  VIEW_VIDEO_MODEL: "VIEW_VIDEO_MODEL",
};
